spring:
  datasource:
    url: jdbc:postgresql://ec2-52-17-1-206.eu-west-1.compute.amazonaws.com:5432/d40msi2fjhfaqa
    username: bmjwctvohiflhq
    password: 04fbba5b865f05685e469207b9003f574e6a6ab8a42db3486c801706f1d083bc
    driver-class-name: org.postgresql.Driver
  jpa.database: POSTGRESQL

csv-input-file: src/main/resources/cropped.csv
